# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa37cab3d95d70411016efb2d90d12496145e68fb3326f2b4151534bb51959f2b0590d7b68673177efc723362c78c12bc87e644d8d641c40cdc35b02155c160d

test:
  secret_key_base: 81948c10d88409ea67b814d66e2b5d49099983bf126bfcb21e1f6c6a0673f9d8bcc274d3846bebf51ad9b73e7ab9c6474f2f6d1d1ce642c11bc6f225ed95fcd3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
